name: Test the profile vanilla and hardened

on: [push, pull_request, release]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian-9']
        suite: ['hardened-nginx', 'vanilla-nginx']
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Chef
      uses: actionshub/chef-install@master
    - name: Install Ruby Deps
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6"
    - name: Bundle install
      run: |
        gem install bundler
        bundle config --global jobs 8
        bundle install   
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@master
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.docker.yml
        KITCHEN_YAML: kitchen.docker.yml