name: Test the profile vanilla and hardened

on: [push, pull_request, release]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian10-nginx-latest']
        suite: ['vanilla', 'hardened']
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Chef
      uses: actionshub/chef-install@master
    - name: accept the chef license
      run: export CHEF_LICENSE=accept-silent
    - name: configure the chef env
      run: echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile
    - name: Source our new bash env
      run: source ~/.bash_profile
    - name: ruby?
      run: | 
        ruby -v
        echo $GEM_HOME
    - name: Setup caching
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        chef gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: look around
      run: |
        ls -alh 
        echo $PATH
        export CHEF_LICENSE=accept
        chef env 
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@master
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.docker.yml
        KITCHEN_YAML: kitchen.docker.yml