name: Test the profile vanilla and hardened

on: [push, pull_request, release]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian10-nginx-latest']
        suite: ['vanilla', 'hardened']
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Chef
      uses: actionshub/chef-install@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6"
   - name: Setup caching
     uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --no-document   
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@master
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.docker.yml
        KITCHEN_YAML: kitchen.docker.yml